### ISSUE TITLE
3x2屏幕导致崩溃

### ISSUE THREAD

**Issue by ptemtawa** [dfdyz/VoidPowerMod#5]
玻璃显示器在由3x1更新至3x2的一瞬间崩溃坏档（1.20.1forge）

[错误报告-2024-11-30_15.39.31.zip](https://github.com/user-attachments/files/17993251/-2024-11-30_15.39.31.zip)

**Comment by dfdyz** [comment]
日志没上传成功

**Comment by dfdyz** [comment]
使用新版的cct(1.113.x)
